feat(ConditionalsEditor): search for plot path
ME3Tweaks/LegendaryExplorer pull request #308
Opened 2022-03-11 16:41 UTC by jherchen

users can now also search for plot path in conditionals editor

2022-03-11 17:25 UTC, henbagle approved these changes

2022-03-11 20:19 UTC, Mgamerz commented
Looks good to me.

2022-03-12 06:32 UTC, SirCxyrtyx requested changes

2022-03-12 06:32 UTC, SirCxyrtyx commented on LegendaryExplorer/LegendaryExplorer/Tools/ConditionalsEditor/ConditionalsEditorWindow.xaml.cs
> +                    string entryPlotPath = entry.PlotPath;
`PlotPath` will be null for any conditional not in the plot database (such as ones from mods), causing an exception to be thrown on the next line.
```suggestion
                    string entryPlotPath = entry.PlotPath ?? "";
```

2022-03-12 13:58 UTC, jherchen commented
Thank you, @SirCxyrtyx

2022-03-12 16:08 UTC, merged

2022-03-12 22:48 UTC, SirCxyrtyx commented
Thanks for contributing!